let result = document.getElementById("result");
console.log(result);
result.style.color = "blue";
result.style.backgroundColor = "yellow";
result.style.margin = "20px";
result.style.padding = "20px";
result.style.fontSize = "18px";
result.style.fontWeight = "bold";
result.style.height = "200px";
result.style.width = "300px";